### ISSUE TITLE
Levelhead API is down

### ISSUE THREAD

**Issue by FixLevelHeadPlz** [CheatBreakerNet/Client#52]
### Describe the bug

Level head still not working and now I cant even lauch the beta branch anymore.

### Steps To Reproduce

Enable levelhead in Hypixel Collection in the mods menu.

### Expected Behavior

Levelhead should show levels above player heads

### Environment

```markdown
OS: Windows 10/11
Game version: 1.8.9
Game build number: bf01d1e
Launcher version: v2.3.6
JRE version: 8u111
```

### Anything else?

The mod is not working for me (windows 11) or my friend (windows 10). We've tried disabling and re-enabling, relogging, restarting the client, etc., but nothing has worked so far. Beta branch worked before but now we can't even launch the game in beta branch.

**Comment by ShonP40** [comment]
1. Beta branch gets deleted every time all its changes get merged into the main branch
2. The API we use for LevelHead started removing endpoints (including the one for player stats) due to Hypixel changing their API policy, we are not the only client affected by these changes

We are currently looking at possible fixes & have no ETA for when it will be fixed

**Comment by Tellinq** [comment]
We will be addressing this in a later update
