### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by Alparo1** [CheatBreakerNet/Client#58]
### Type

Client

### What is your username?

Alparo_

### Describe the reason of your punishment (or the reason you think you were punished for)

When I try to log on my account it says I'm banned, as far as I remember, before I got banned I was looking at perspective mod and then my client crashed, after I tried to relaunch the client, it said I'm banned.

### Describe why we should revoke your punishment

False banned.

**Comment by Tellinq** [comment]
Hey there, I was the one who banned you as I was noticing your crash logs were going off like mad. I primarily did this to stop those notifications from coming through *and* to ensure word gets out that your specific crash is a user issue and not us. You are unbanned now. This should not happen again and we will ensure we have less alarming notifications to inform users of the actual issue instead of stopping them from actually playing.

The reason we got your crash logs is because of `No OpenGL context found in the current thread`. Based off the GPU you have, it looks like you might have corrupted drivers. Before you continue playing, I highly recommend you reinstall your GPU drivers. When GPU drivers get corrupted, I don’t recommend you use GeForce Experience or simply just using an installer to install your drivers. Before that, I recommend using a tool called Display Driver Uninstaller (or DDU) to completely flush out your current drivers. That way NVIDIA’s installer will *actually* perform a true clean install. 

NVIDIA and AMD do have a “Perform a Clean Install” button, but what happens is some files are assumed to never be touched and are thus skipped, but that is not always true and can get corrupted at any point (whether through installation or if an application tampered with your driver files). DDU will assist with a true clean install.

If you’re accustomed to installing drivers via GeForce Experience, please refer to NVIDIA’s official page for drivers and DO NOT use GeForce Experience. Just select what matcher your GPU and operating system, and either select the following based on your criteria:
- Game Ready Drivers **IF** you are primarily trying new games or need the latest performance/image improvements
- Studio Drivers **IF** you crave stability over anything else

https://www.nvidia.com/en-us/geforce/drivers/


Follow these steps in order:
1. Install Display Driver Uninstaller
    - You can easily do this with Winget by opening Command Prompt and type in `winget install Wagnardsoft.DisplayDriverUninstaller`
2. Reboot into Safe Mode
    1. Hold the LEFT SHIFT key **before** pressing the Windows Key and **until** you see the “Please Wait” screen
    2. If on Windows 11, your system may reboot prior to seeing the Shutdown Options menu
    3. Go into each menu as follows: Troubleshoot -> Advanced Options -> Startup Settings -> Restart
    4. Upon rebooting, press `4` to enter Safe Mode (without internet)
    5. Enter the password for your account (note that Windows Hello authentication will not work)
    6. Open DDU
    7. Make sure the last option to stop drivers from installing through Windows Update is checked. This is to stop any potential outdated drivers from interrupting your intended driver installation
    8. Select GPU as the type in DDU
    9. Your brand should automatically appear. If it is incorrect, you may have a secondary graphics processor (such as an Integrated Graphics Processor Unit). Make sure your brand is selected.
    10. Press Clean and Restart
    11. Your system will automatically reboot into your normal environment
    12. Do note that upon restart, some of your startup applications will not actually start up as some are dependent on a graphics driver. Also be mindful that you will still only be able to use one monitor until you install your drivers
    13. Install your GPU drivers
        - You can use either Express or Custom. The same effect will happen either way.
